// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugdsxmuodkpuwpteubfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnZHN4bXVvZGtwdXdwdGV1YmZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMDQ2MjAsImV4cCI6MjA3MDg4MDYyMH0.mMhJExOxxiJh5kzbve_1vJZaoZjWuOKdbXVD8rEEtD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});